################################################################################
#                 Continuous Integration Control for Travis CI                 #
#                                                                              #
# This file controls the build and test process run on Travis CI on every push #
# to the master branch. It runs the test suite and then produces a tarpaulin   #
# coverage report.                                                             #
################################################################################

language: rust
sudo: required
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

dist: trusty
addons:
  apt:
    packages:
      - libssl-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
- cargo clean
- cargo build --all-features
- cargo test --all-features

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
    echo "Uploaded code coverage"
  fi
